/*
ND visas imanomas kombinacijos su 4 booleanais 128
*/
let a = 1;
console.log(a,true && true && true && true);
a += 1;
console.log(a,true && true && true && false);
a += 1;
console.log(a,true && true && false && false);
a += 1;
console.log(a,true && false && false && false);
a += 1;
console.log(a,false && false && false && false);
a += 1;
console.log(a,false && true && true && true);
a += 1;
console.log(a,false && false && true && true);
a += 1;
console.log(a,false && false && false && true);
a += 1;
console.log(a,true && false && true && false);
a += 1;
console.log(a,false && true && false && true);
a += 1;
console.log(a,true && false && false && true);
a += 1;
console.log(a,false && true && true && false);
a += 1;
console.log(a,false && false && true && false);
a += 1;
console.log(a,false && true && false && false);
a += 1;
console.log(a,true && false && true && true);
a += 1;
console.log(a,true && true && false && true);
// 16
a += 1;
console.log(a,true && true && true || true);
a += 1;
console.log(a,true && true && true || false);
a += 1;
console.log(a,true && true && false || false);
a += 1;
console.log(a,true && false && false || false);
a += 1;
console.log(a,false && false && false || false);
a += 1;
console.log(a,false && true && true || true);
a += 1;
console.log(a,false && false && true || true);
a += 1;
console.log(a,false && false && false || true);
a += 1;
console.log(a,true && false && true || false);
a += 1;
console.log(a,false && true && false || true);
a += 1;
console.log(a,true && false && false || true);
a += 1;
console.log(a,false && true && true || false);
a += 1;
console.log(a,false && false && true || false);
a += 1;
console.log(a,false && true && false || false);
a += 1;
console.log(a,true && false && true || true);
a += 1;
console.log(a,true && true && false || true);
// 32
a += 1;
console.log(a,true && true || true && true);
a += 1;
console.log(a,true && true || true && false);
a += 1;
console.log(a,true && true || false && false);
a += 1;
console.log(a,true && false || false && false);
a += 1;
console.log(a,false && false || false && false);
a += 1;
console.log(a,false && true || true && true);
a += 1;
console.log(a,false && false || true && true);
a += 1;
console.log(a,false && false || false && true);
a += 1;
console.log(a,true && false || true && false);
a += 1;
console.log(a,false && true || false && true);
a += 1;
console.log(a,true && false || false && true);
a += 1;
console.log(a,false && true || true && false);
a += 1;
console.log(a,false && false || true && false);
a += 1;
console.log(a,false && true || false && false);
a += 1;
console.log(a,true && false || true && true);
a += 1;
console.log(a,true && true || false && true);
// 48
a += 1;
console.log(a,true || true && true && true);
a += 1;
console.log(a,true || true && true && false);
a += 1;
console.log(a,true || true && false && false);
a += 1;
console.log(a,true || false && false && false);
a += 1;
console.log(a,false || false && false && false);
a += 1;
console.log(a,false || true && true && true);
a += 1;
console.log(a,false || false && true && true);
a += 1;
console.log(a,false || false && false && true);
a += 1;
console.log(a,true || false && true && false);
a += 1;
console.log(a,false || true && false && true);
a += 1;
console.log(a,true || false && false && true);
a += 1;
console.log(a,false || true && true && false);
a += 1;
console.log(a,false || false && true && false);
a += 1;
console.log(a,false || true && false && false);
a += 1;
console.log(a,true || false && true && true);
a += 1;
console.log(a,true || true && false && true);
// 64
a += 1;
console.log(a,true && true || true || true);
a += 1;
console.log(a,true && true || true || false);
a += 1;
console.log(a,true && true || false || false);
a += 1;
console.log(a,true && false || false || false);
a += 1;
console.log(a,false && false || false || false);
a += 1;
console.log(a,false && true || true || true);
a += 1;
console.log(a,false && false || true || true);
a += 1;
console.log(a,false && false || false || true);
a += 1;
console.log(a,true && false || true || false);
a += 1;
console.log(a,false && true || false || true);
a += 1;
console.log(a,true && false || false || true);
a += 1;
console.log(a,false && true || true || false);
a += 1;
console.log(a,false && false || true || false);
a += 1;
console.log(a,false && true || false || false);
a += 1;
console.log(a,true && false || true || true);
a += 1;
console.log(a,true && true || false || true);
// 80
a += 1;
console.log(a,true || true || true && true);
a += 1;
console.log(a,true || true || true && false);
a += 1;
console.log(a,true || true || false && false);
a += 1;
console.log(a,true || false || false && false);
a += 1;
console.log(a,false || false || false && false);
a += 1;
console.log(a,false || true || true && true);
a += 1;
console.log(a,false || false || true && true);
a += 1;
console.log(a,false || false || false && true);
a += 1;
console.log(a,true || false || true && false);
a += 1;
console.log(a,false || true || false && true);
a += 1;
console.log(a,true || false || false && true);
a += 1;
console.log(a,false || true || true && false);
a += 1;
console.log(a,false || false || true && false);
a += 1;
console.log(a,false || true || false && false);
a += 1;
console.log(a,true || false || true && true);
a += 1;
console.log(a,true || true || false && true);
// 96
a += 1;
console.log(a,true || true && true || true);
a += 1;
console.log(a,true || true && true || false);
a += 1;
console.log(a,true || true && false || false);
a += 1;
console.log(a,true || false && false || false);
a += 1;
console.log(a,false || false && false || false);
a += 1;
console.log(a,false || true && true || true);
a += 1;
console.log(a,false || false && true || true);
a += 1;
console.log(a,false || false && false || true);
a += 1;
console.log(a,true || false && true || false);
a += 1;
console.log(a,false || true && false || true);
a += 1;
console.log(a,true || false && false || true);
a += 1;
console.log(a,false || true && true || false);
a += 1;
console.log(a,false || false && true || false);
a += 1;
console.log(a,false || true && false || false);
a += 1;
console.log(a,true || false && true || true);
a += 1;
console.log(a,true || true && false || true);
// 112
a += 1;
console.log(a,true || true || true || true);
a += 1;
console.log(a,true || true || true || false);
a += 1;
console.log(a,true || true || false || false);
a += 1;
console.log(a,true || false || false || false);
a += 1;
console.log(a,false || false || false || false);
a += 1;
console.log(a,false || true || true || true);
a += 1;
console.log(a,false || false || true || true);
a += 1;
console.log(a,false || false || false || true);
a += 1;
console.log(a,true || false || true || false);
a += 1;
console.log(a,false || true || false || true);
a += 1;
console.log(a,true || false || false || true);
a += 1;
console.log(a,false || true || true || false);
a += 1;
console.log(a,false || false || true || false);
a += 1;
console.log(a,false || true || false || false);
a += 1;
console.log(a,true || false || true || true);
a += 1;
console.log(a,true || true || false || true);
//128